spring:
  application:
    name: xkBase
  datasource:
    url: jdbc:mysql://localhost:3306/xkbase?useSSL=false&serverTimezone=UTC
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: #Hibernate 提示数据库版本和隔离级别未定义。虽然不影响功能，但建议明确配置：
      minimum-idle: 5         # 最小空闲连接数
      maximum-pool-size: 10   # 最大连接池大小
      connection-test-query: SELECT 1  # 测试连接的 SQL
  jpa:
    hibernate:
      ddl-auto: update        # 自动更新表结构（仅用于开发阶段，生产环境建议使用 none）
    show-sql: true            # 显示 SQL
    open-in-view: false       # 禁用 Open-in-View，适用于纯 API 项目
    properties:
        hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.MySQLDialect
            jdbc:
                time_zone: Asia/Taipei
jwt:
  secret: e9c63d1db6b6ad97ee7b1828c6291f38c06abed917b8626892e9113d4e33302a17a04fbcf2d8b63d3abecd733c6d98a360c91e50d2f1675b9583d31ddcb93e13

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: WARN
server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
